[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "4dgb"
authors = [{name = "David H. Rogers", email = "dhr@lanl.gov"}]
dynamic = ["version", "description"]


